add open_datatree to xarray (#8697)
* DAS-2060: Skips datatree_ CI

Adds additional ignore to mypy

Adds additional ignore to doctests

Excludes xarray/datatree_ from all pre-commmit.ci

* DAS-2070: Migrate open_datatree into xarray.

First stab. Will need to add/move tests.

* DAS-2060: replace relative import of datatree to library

* DAS-2060: revert the exporting of NodePath from datatree

I mistakenly thought we wanted to use the hidden version of datatree_ and we do not.

* Don't expose open_datatree at top level

We do not want to expose open_datatree at top level until all of the code is migrated.

* Point datatree imports to xarray.datatree_.datatree

* Updates function signatures for mypy.

* Move io tests, remove undefined reference to documentation.

Also starts fixing simple mypy errors

* Pass bare-minimum tests.

* Update pyproject.toml to exclude imported datatree_ modules.

Add some typing for mygrated tests.
Adds display_expand_groups to core options.

* Adding back type ignores

This is cargo-cult.  I wonder if there's a different CI test that wanted these
and since this is now excluded at the top level.  I'm putting them back until
migration into main codebase.

* Refactor open_datatree back together.

puts common parts in common.

* Removes TODO comment

* typo fix

Co-authored-by: Tom Nicholas <tom@cworthy.org>

* typo 2

Co-authored-by: Tom Nicholas <tom@cworthy.org>

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* Call raised exception

* Add unpacking notation to kwargs

* Use final location for DataTree doc strings

Co-authored-by: Justus Magin <keewis@users.noreply.github.com>

* fix comment from open_dataset to open_datatree

Co-authored-by: Justus Magin <keewis@users.noreply.github.com>

* Revert "fix comment from open_dataset to open_datatree"

This reverts commit aab1744d52a466ac03829cda171c09beb1cc0704.

* Change sphynx link from meth to func

* Update whats-new.rst

* Fix what-new.rst formatting.

---------

Co-authored-by: Tom Nicholas <tom@cworthy.org>
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Co-authored-by: Justus Magin <keewis@users.noreply.github.com>