Shallow copy parent and children in DataTree constructor (#9297)
* add tests

* fix by shallow copying

* correct first few tests

* replace constructors in tests with DataTree.from_dict

* rewrite simple_datatree fixture to use DataTree.from_dict

* fix incorrect creation of nested tree in formatting test

* Update doctests for from_dict constructor

* swap i and h in doctest example for clarity.

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* Fix a few mypy errors.

* Bonkers way to set type checking

I will happily take something better.

But this was the error I was getting

xarray/tests/test_datatree.py:127: error: Argument 1 to "relative_to" of
"NamedNode" has incompatible type "DataTree[Any] | DataArray"; expected
"NamedNode[Any]"  [arg-type]

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* Removes parent keyword from DataTree constructor

But it doesn't fix all the tests There's three tests that I don't fully know
what should be tested or if they still make sense.

* fix test_setparent_unnamed_child_node_fails

* fix test_dont_modify_parent_inplace -> bug?

* fix test_create_two_children

* make .parent read-only, and remove tests which test the parent setter

* update error message to reflect fact that .children is Frozen

* fix another test

* add test that parent setter tells you to set children instead

* fix mypy error due to overriding settable property with read-only property

* fix test by not trying to set parent via kwarg

---------

Co-authored-by: Matt Savoie <matthew.savoie@colorado.edu>
Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>