Better error message for variables with same name as a dimension
We now get:

	In [2]: xray.Dataset({'x': (('x', 'y'), [[1]])})
	ValueError: the variable 'x' has the same name as one of its
	dimensions ('x', 'y'), but it is not 1-dimensional and thus
	it is not a valid index