Attempt fixing typing errors
Mixing in DatasetReduce fixes:
xarray/tests/test_groupby.py:460: error: Invalid self argument "Dataset" to attribute function "mean" with type "Callable[[DatasetReduce, Optional[Hashable], Optional[bool], Optional[bool], KwArg(Any)], T_Dataset]"  [misc]

Switching to "Dateset" as returned type fixes:

xarray/tests/test_groupby.py:77: error: Need type annotation for "expected"  [var-annotated]