Marks slow, flaky, and failing tests (#1336)
* Adds marked tests as slow, flakey, and optionalci

Tests are marked using the following py.test options:

 * @slow which is run on default, not run if `--skip-slow`.
 * @optionalci is run on default, not run if `--skip-optional-ci`
 * @flakey which is not run on default, run if `--run-flakey`

Note, the `optionalci` category is needed in order to mark
tests that are environment dependent when run on continuous
integration (CI) hardware, e.g., tests that fail due to
variable loads on travis CI.

* Spelling: flakey -> flaky

* Test suite adjustments

* Typos

* Remove bottleneck from most CI builds

* xfail for cross engine read write netcdf4

* Try fix: Closes open file (for Windows error)

```
WindowsError: [Error 32] The process cannot access the file because it
is being used by another process
```

* Try fix: Closes open file (for Windows error)

```
WindowsError: [Error 32] The process cannot access the file because it
is being used by another process
```