FIX: `assert_identical` now considers `xindexes` + improve `RangeIndex` equals (#11035)
* FIX: assert_identical compares xindexes

* move logic to be more consistent

* combine tests to simplify

* add reprs to dataset fixtures

* update formatting tests

* backcompat to escape index checks

* make range_index equals float error tolerant

* RangeIndex whatsnew

* clean up whatsnew

* better index value diff formatting

* formatting change tests

* fix test_concat test

Without this you get:

AssertionError: Left and right Dataset objects are not identical
Differing indexes:
L   x                    IntervalIndex([(-1, 0], (0, 1]],
dtype='interval[int64, right]', name='x')
R   x                    Index([(-1, 0], (0, 1]], dtype='object',
name='x')

* update groupby tests for IntervalIndex

* correct timedelta encoding in test

just matching what it is set to above. this was not caught before by
assert_identical

* escape remaining failing tests with TODO notes

* remove over-verbose AI addition