Try fix: Closes open file (for Windows error)
```
WindowsError: [Error 32] The process cannot access the file because it
is being used by another process
```