Validate output dimension sizes with apply_ufunc (#2155)
* Validate output dimension sizes with apply_ufunc

Fixes GH1931

Uses of apply_ufunc that change dimension size now raise an explicit error,
e.g.,

    >>> xr.apply_ufunc(lambda x: x[:5], xr.Variable('x', np.arange(10)))
    ValueError: size of dimension 'x' on inputs was unexpectedly changed by
    applied function from 10 to 5. Only dimensions specified in ``exclude_dims``
    with xarray.apply_ufunc are allowed to change size.

* lint

* More output validation for apply_ufunc