Squash merge #5950
Squashed commit of the following:

commit 6916fa7debfe4ca5c5ce9796fe5fe3243d6c4d2a
Author: Deepak Cherian <dcherian@users.noreply.github.com>
Date:   Mon Nov 22 11:16:43 2021 -0700

    Update xarray/util/generate_reductions.py

    Co-authored-by: Illviljan <14371165+Illviljan@users.noreply.github.com>

commit cd8a898d5b003ea28ec8f3feacb56d76b6dc1096
Author: dcherian <deepak@cherian.net>
Date:   Sat Nov 20 14:37:17 2021 -0700

    add doctests

commit 19d82cddf0a4ac30811803de9f7e70a881d52ea0
Author: Illviljan <14371165+Illviljan@users.noreply.github.com>
Date:   Sat Nov 20 22:00:29 2021 +0100

    more reduce

commit 0f94bec2953aa3e7eadd0c4efc25cd6111b7e663
Author: Illviljan <14371165+Illviljan@users.noreply.github.com>
Date:   Sat Nov 20 20:48:27 2021 +0100

    another reduce

commit be33560a14ac4b9379e5d0ff4f340cfbd6d552f1
Author: Illviljan <14371165+Illviljan@users.noreply.github.com>
Date:   Sat Nov 20 20:28:39 2021 +0100

    one more reduce

commit 3d854e52055de0f53f4ba16b0713ac581611ef94
Author: Illviljan <14371165+Illviljan@users.noreply.github.com>
Date:   Sat Nov 20 20:21:26 2021 +0100

    more reduce edits

commit 2bbddafaacf46f65c950738a9db3cbaddb198763
Author: Illviljan <14371165+Illviljan@users.noreply.github.com>
Date:   Sat Nov 20 20:12:31 2021 +0100

    make reduce args consistent

commit dfbe103c3425ba4d8aa91095ec5b7386fb785225
Merge: f03b67592 dd28a57f6
Author: Illviljan <14371165+Illviljan@users.noreply.github.com>
Date:   Sat Nov 20 19:01:59 2021 +0100

    Merge branch 'generate-reductions-class' of https://github.com/dcherian/xarray into pr/5950

commit f03b67592cbff91172a50213cf0f9621062114cb
Merge: 411d75d5c 7a201de64
Author: Illviljan <14371165+Illviljan@users.noreply.github.com>
Date:   Sat Nov 20 19:01:42 2021 +0100

    Merge branch 'main' into pr/5950

commit dd28a57f66188db47a05fad184519295d688213d
Author: dcherian <deepak@cherian.net>
Date:   Sat Nov 20 10:57:22 2021 -0700

    updates

commit 6a9a1240aa95d71ef2081f6e98152981f9db336d
Author: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Date:   Sat Nov 20 17:02:07 2021 +0000

    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci

commit 411d75d5ced18349968c060918e9bdcd4be04537
Author: Illviljan <14371165+Illviljan@users.noreply.github.com>
Date:   Sat Nov 20 18:00:08 2021 +0100

    Now get normal code running as well

    Protocols are not needed anymore when subclassing/defining directly in the class.

    When adding a dummy method in DatasetResampleReductions the order of subclassing had to be changed so the correct reduce was used.

commit 5dcb5bfebe04302beb732259f3e805bd31691ed8
Author: Illviljan <14371165+Illviljan@users.noreply.github.com>
Date:   Sat Nov 20 12:30:50 2021 +0100

    Attempt fixing typing errors

    Mixing in DatasetReduce fixes:
    xarray/tests/test_groupby.py:460: error: Invalid self argument "Dataset" to attribute function "mean" with type "Callable[[DatasetReduce, Optional[Hashable], Optional[bool], Optional[bool], KwArg(Any)], T_Dataset]"  [misc]

    Switching to "Dateset" as returned type fixes:

    xarray/tests/test_groupby.py:77: error: Need type annotation for "expected"  [var-annotated]

commit 7a201de643515aec9a0c88dc78253499528fa99f
Author: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>
Date:   Fri Nov 19 11:37:20 2021 -0700

    [pre-commit.ci] pre-commit autoupdate (#5990)

commit 95394d5bcbd7d73bae34c091a080c42bcfc9f07d
Author: Illviljan <14371165+Illviljan@users.noreply.github.com>
Date:   Mon Nov 15 21:40:37 2021 +0100

    Use set_options for asv bottleneck tests (#5986)

    * Use set_options for bottleneck tests

    * Use set_options in rolling

    * Update rolling.py

    * [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci

    * Update rolling.py

    * Update rolling.py

    * set_options not needed.

    Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

commit b2d7cd8837ea9b3e7e0eb0390479a1986f62d4b4
Author: Kai Mühlbauer <kmuehlbauer@users.noreply.github.com>
Date:   Mon Nov 15 18:33:43 2021 +0100

    Fix module name retrieval in `backend.plugins.remove_duplicates()`, plugin tests (#5959)

    Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

commit c7e9d9647f2c7df7e5b14644926dc2126ad4318f
Author: dcherian <deepak@cherian.net>
Date:   Wed Nov 10 11:49:47 2021 -0700

    Minor improvement

commit dea8fd9f326a543807c26b6a62e84b28b5cb4cc3
Author: dcherian <deepak@cherian.net>
Date:   Mon Nov 8 16:18:07 2021 -0700

     REfactor

commit 9bb2c321e8df2f5978c40a1c3c8f891c77e847ff
Author: dcherian <deepak@cherian.net>
Date:   Mon Nov 8 13:56:53 2021 -0700

    Reorder docstring to match numpy

commit 99bfe128066ec3ef1b297650a47e2dd0a45801a8
Author: dcherian <deepak@cherian.net>
Date:   Mon Nov 8 12:44:23 2021 -0700

    Fixes #5898

commit 7f39cc0d8c664e3fcf354536ed3a95882064b4b6
Author: dcherian <deepak@cherian.net>
Date:   Mon Nov 8 12:39:00 2021 -0700

    Minor docstring improvements.

commit a04ed824a55b757937a4db4aa65729dccf62c1a7
Author: dcherian <deepak@cherian.net>
Date:   Mon Nov 8 12:35:48 2021 -0700

    Small changes

commit 816e7941e47b14280103d5d10da94139f394c0cd
Author: dcherian <deepak@cherian.net>
Date:   Sun Nov 7 20:56:37 2021 -0700

    Generate DataArray, Dataset reductions too.

commit 569c67f28b3e7ff4c475793325a4388220932d02
Author: dcherian <deepak@cherian.net>
Date:   Sun Nov 7 20:54:42 2021 -0700

    Add ddof for var, std

commit 6b9a81a6fbe3ba460d905f0e92105d8e25af3ebb
Author: dcherian <deepak@cherian.net>
Date:   Sun Nov 7 20:35:52 2021 -0700

    Better generator for reductions.